name: Python CI

on:
  workflow_dispatch:
    inputs:
      max_workers:
        description: 'Número de hilos para paralelizar ranuras'
        required: false
        default: '12'
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TZ: America/Lima   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo .env desde secrets
        run: |
          echo "GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> .env
          echo "GITHUB_OWNER=${{ secrets.MY_GITHUB_OWNER }}" >> .env
          echo "GITHUB_REPO=${{ secrets.MY_GITHUB_REPO }}" >> .env
          echo "AZURE_TOKEN=${{ secrets.MY_AZURE_TOKEN }}" >> .env
          echo "AZURE_ORG=${{ secrets.MY_AZURE_ORG }}" >> .env
          echo "AZURE_PROJECT=${{ secrets.MY_AZURE_PROJECT }}" >> .env
          echo "AZURE_REPO_ID=${{ secrets.MY_AZURE_REPO_ID }}" >> .env

      - name: Run main script
        run: python run_all.py

      - name: Subir reporte generado como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-migracion
          path: reports/**

